<?php
/**
 * @file
 * doable_taxonomies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function doable_taxonomies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Climate Change Adaptation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '009f15f9-f27f-4202-be55-6f14e23c3a6c',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Petroleum',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0413cf88-8e20-4a40-8204-38195cfb9ef4',
    'vocabulary_machine_name' => 'carbon_sources',
  );
  $terms[] = array(
    'name' => 'Recycling',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '07718c2d-0dab-4e3e-9b53-3754dadec8c1',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Carbon Dioxide (CO2)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '0d42a365-49ce-40a9-9e20-056f2be03cca',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => 'Carbon',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0d6c40b0-84d8-4b50-be6d-8312afea9c2c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Fuels',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '108692b1-6008-4568-b224-64c4aac0f13b',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Perfluorocarbons (PFCs)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1a0509ec-3fc8-4757-99e1-e4d025f97409',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => 'Perfluorocarbons (PFCs)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1a91e4c3-9f27-4433-9c6e-411cd58f894b',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => 'Petroleum',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '1bbe09d3-62d8-4935-a950-86ca19980e03',
    'vocabulary_machine_name' => 'carbon_sources',
  );
  $terms[] = array(
    'name' => 'Global',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '1d27ede9-c9d3-48b7-a87c-071c80acd93a',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Bike Sharing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e03c650-31e4-4a23-aef5-4a4862ca1097',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Town',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '23b64755-938c-49be-b33a-3b421e419792',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Natural Gas',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '24cd38c8-f781-4fe8-8fe2-3025a9622c1a',
    'vocabulary_machine_name' => 'carbon_sources',
  );
  $terms[] = array(
    'name' => '$5M to $9.9M',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '262ead51-5df0-4ee7-893a-4fcb40c33631',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Reduce Our Demand',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '27543d69-b661-4608-92d8-408b8c1c4619',
    'vocabulary_machine_name' => 'solution_strategy',
  );
  $terms[] = array(
    'name' => 'Boston',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2e198652-6793-4cdb-b639-03ffbe095d1c',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Neighborhood',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '348e2981-4fef-4690-a284-96bfdc90b96a',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Decarbonize Our Energy and Fuel Supply',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '391bb05c-8d03-4661-82b4-9a740350b368',
    'vocabulary_machine_name' => 'solution_strategy',
  );
  $terms[] = array(
    'name' => 'Security',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3befd8da-eb6f-409c-83b9-c636ad03d67f',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'None',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '3d53db8d-75aa-4ac0-b7f8-7c1faddc3c2c',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Transportation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '40b29e16-9ec8-47a3-8b20-f3037f9756f1',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '$ Billions',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '455cdfff-c79f-4fdd-8754-6b2c5c848ae6',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Energy - Coal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4c87e74f-e6eb-471a-a005-8b3872cfd0b7',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Use',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '4e033c4c-7cf5-43f9-9f92-ec9aa15c32cd',
    'vocabulary_machine_name' => 'energy_cycle',
  );
  $terms[] = array(
    'name' => 'Continent',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => '504228fb-add9-4bf3-b0bc-85cbb0f8cfef',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Financing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5264156d-8f81-4564-9254-31d961c90f58',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'City',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '55ecf163-2590-435e-825e-559fc7bcefe4',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Agricultural',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '569c6add-f912-42fe-a4a7-2a79cf62db93',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Water',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '59c1c904-5e81-4aed-b851-dac24ab93483',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Days',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5a230d64-ae13-4f4f-a92f-2c86ef42d549',
    'vocabulary_machine_name' => 'timeline',
  );
  $terms[] = array(
    'name' => 'Cycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5a6047bb-66ca-457d-9a28-93a7f6e28bcc',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Crowd-Funding',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '65e7b09a-7cdb-4c0a-abda-50583f429161',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Suburban',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '6a5eed12-1d5d-4a2d-92be-409f800f55f3',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'The Built Environment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6cdb1607-6043-4a27-b6b5-c14d3c9c8df1',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Water',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6cfa3b7d-cac0-4c46-8d51-04434233b26b',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Al Gore',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '703a3bb9-d096-442a-8630-32705a2ef8da',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Natural Gas',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '705cf984-21fc-40fe-8cf0-067e79638dc5',
    'vocabulary_machine_name' => 'carbon_sources',
  );
  $terms[] = array(
    'name' => 'Nitrogen Trifluoride* (NF3)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '74079223-c87d-46aa-9f1a-9e72be0cfd21',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => 'Years',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '74163746-8594-4d38-92fd-e0d68fec4f0c',
    'vocabulary_machine_name' => 'timeline',
  );
  $terms[] = array(
    'name' => 'Paris',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '749e1af6-0b15-4978-ace0-cbdfaff26343',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Green Buildings',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '750cb83f-cc58-4d65-910a-153b6d20ce44',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Coal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7894487d-79bf-4d77-8048-95b819da5c4b',
    'vocabulary_machine_name' => 'carbon_sources',
  );
  $terms[] = array(
    'name' => 'Infrastructure',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7d2fdc1f-fcd8-438b-8542-0cb5a947f72f',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'NGO',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '7e36926d-fab3-425b-ba44-71eb6fd803bd',
    'vocabulary_machine_name' => 'sponsor',
  );
  $terms[] = array(
    'name' => 'Natural Lands',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '81242362-a025-4652-aa7f-fbfa17ca7928',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Weeks',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '82690106-c5d9-4eb2-b17c-cb70b927553c',
    'vocabulary_machine_name' => 'timeline',
  );
  $terms[] = array(
    'name' => 'Methane (CH4)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '839cbcc8-6892-4e09-96fb-f876bec6efca',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => 'Public Health',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '879ec25a-9bfd-41d6-ad1f-7f8add46f87d',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Energy-Electricity',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '88ee78d2-de6e-464a-aec7-f50db824cadf',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Carbon Emissions Reduction',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8abaf9ed-d38b-427e-a89c-4665bc8bbdc6',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Montreal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b0d5096-02f4-4e10-803e-79f9d19aef1e',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '$25M to $100M',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8b86881f-150b-456f-b6d7-c915096db93b',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Crowd-Sourcing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8c4a1f79-2fd2-4091-a4c3-58e1c0a7c5ee',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => '$100M+',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8ee678e4-8af1-40b1-b40a-683f2f11ed77',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => '$ Thousands',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '90707d33-270a-413e-9e07-b5ef86c4a509',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Rural',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '9312682f-6f83-4a7c-b331-2f6ca2033ff4',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Cap-and-Trade Regulation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '978a0fec-9b6e-4001-8af5-95314f39edbb',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => '$100 to $999K',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '9fca7403-d4f1-4186-8676-c1ccb7e4393d',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Encourage Efficiency',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a67deb88-dd51-4df8-812d-9c3830b792af',
    'vocabulary_machine_name' => 'solution_strategy',
  );
  $terms[] = array(
    'name' => 'Chatanooga',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8987eba-77c3-4a39-862e-81337f6d1240',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Months',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'abbec439-7002-46b1-926a-bae239aeeba9',
    'vocabulary_machine_name' => 'timeline',
  );
  $terms[] = array(
    'name' => 'Public Education',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ae43e7dc-c342-4ecb-97be-56a5ddb2fce8',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Community Building',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bc19a3c2-2563-4ad8-a3d4-e020ae9277bf',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Solar',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc4263aa-d777-4f6a-94d5-a25e2c84b871',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Land Use',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bd0b55ee-6ebc-4667-b020-b39ef4240d57',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'New York City',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bfd08534-8e57-4c04-8170-5710e61f41ce',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'Sustainable Mobility',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c3cd63c5-984c-4e7d-9b55-af68c35505d7',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Country',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'c724ff18-a208-4f14-930d-1ba025a4e539',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => '$10M to $24.9M',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cdecc208-b7ee-4db6-b9f3-7225c30ccd53',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Nitrous Oxide (N2O)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cf18cd66-c88b-4ff3-90cf-6c709fb8f4a3',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => 'Coal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd0fb445d-e329-4f89-8688-aef61ea23425',
    'vocabulary_machine_name' => 'carbon_sources',
  );
  $terms[] = array(
    'name' => 'Hydrofluorocarbons (HFCs)',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd21d2adc-85e9-429f-a9f8-34f6f409be99',
    'vocabulary_machine_name' => 'emission_type',
  );
  $terms[] = array(
    'name' => '$ Millions',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'd67219eb-9f27-4d5c-a769-c3942e771c09',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => '$1M to $4.99M',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd7968dcb-6a37-4fd3-af48-c4a523230dff',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Private Company',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'daac54d6-47e5-42a7-99d0-1938a51a4b61',
    'vocabulary_machine_name' => 'sponsor',
  );
  $terms[] = array(
    'name' => 'Transmission',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dd33cf1d-96f2-47ff-a490-e4a597065182',
    'vocabulary_machine_name' => 'energy_cycle',
  );
  $terms[] = array(
    'name' => '$0 to $10K',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dd9d5c05-a5f4-464e-9f81-74db9649cfc7',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Generation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dfb34f45-7d1b-404e-bd87-5fdf3e624dde',
    'vocabulary_machine_name' => 'energy_cycle',
  );
  $terms[] = array(
    'name' => 'State/Province',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'dffb56f4-822e-4c27-8e55-974f444b4429',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => '$10 to $100K',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e39ec0f6-c168-4f7d-9f86-5ff0b533e5a2',
    'vocabulary_machine_name' => 'budget',
  );
  $terms[] = array(
    'name' => 'Decades',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'e3e49d88-c197-41ce-9bca-7d91eda9f6e6',
    'vocabulary_machine_name' => 'timeline',
  );
  $terms[] = array(
    'name' => 'Waste',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'e84d2a14-0196-41c6-ad9c-caa70e73474a',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Renewable Energy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ec8bab54-d4e9-45b8-8e98-2892064f028b',
    'vocabulary_machine_name' => 'sector',
    'field_sector_icon' => array(),
    'field_sector_image' => array(),
  );
  $terms[] = array(
    'name' => 'Clean Water',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1446fdf-b254-453d-bcad-3c40d78bf531',
    'vocabulary_machine_name' => 'tags',
  );
  $terms[] = array(
    'name' => 'NGO',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f2b6419d-e108-427d-bba2-6464636bcc9e',
    'vocabulary_machine_name' => 'sponsor',
  );
  $terms[] = array(
    'name' => 'Energy- Natural Gas',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f34dc982-3594-4e00-b1b5-1a1fb6e113f7',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'International',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => 'f4289b2a-22c7-4b6d-ad7c-a97f88b69876',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Transportation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f7ba8f8a-3d6a-437d-909e-38bd24cdf1e4',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Industrial',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f7cb373e-e31b-4747-87d2-a348ec77261e',
    'vocabulary_machine_name' => 'solution_type',
  );
  $terms[] = array(
    'name' => 'Regional',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'fa598c67-9b99-4551-a36b-baaf912dfeed',
    'vocabulary_machine_name' => 'density',
  );
  $terms[] = array(
    'name' => 'Governmental Body',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'fc92be21-f534-4458-ae55-601d463ef1a6',
    'vocabulary_machine_name' => 'sponsor',
  );
  return $terms;
}
